spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5434/taskMaster
security:
  user:
    service:
      default-role: ROLE_USER
  jwt:
    lifetime: 40m
    secret: MLSBFsguybjkndkanjidh1uy1231nkdajhDAsda1w1dsad1SADa

