spring:
  application:
    name: config-client
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        bootstrap: true
      profile: test
server:
  port: 8060